export const countries = [
    { code: "AD", countryEn: "Andorra", countryAr: "أندورا", phone: "376" },
  { code: "AE", countryEn: "United Arab Emirates", countryAr: "الإمارات العربية المتحدة", phone: "971" },
  { code: "AF", countryEn: "Afghanistan", countryAr: "أفغانستان", phone: "93" },
  { code: "AG", countryEn: "Antigua and Barbuda", countryAr: "أنتيغوا وبربودا", phone: "1-268" },
  { code: "AI", countryEn: "Anguilla", countryAr: "أنغويلا", phone: "1-264" },
  { code: "AL", countryEn: "Albania", countryAr: "ألبانيا", phone: "355" },
  { code: "AM", countryEn: "Armenia", countryAr: "أرمينيا", phone: "374" },
  { code: "AO", countryEn: "Angola", countryAr: "أنغولا", phone: "244" },
  { code: "AQ", countryEn: "Antarctica", countryAr: "القارة القطبية الجنوبية", phone: "672" },
  { code: "AR", countryEn: "Argentina", countryAr: "الأرجنتين", phone: "54" },
  { code: "AS", countryEn: "American Samoa", countryAr: "ساموا الأمريكية", phone: "1-684" },
  { code: "AT", countryEn: "Austria", countryAr: "النمسا", phone: "43" },
  { code: "AU", countryEn: "Australia", countryAr: "أستراليا", phone: "61", "suggested": true },
  { code: "AW", countryEn: "Aruba", countryAr: "أروبا", phone: "297" },
  { code: "AX", countryEn: "Alland Islands", countryAr: "جزر آلاند", phone: "358" },
  { code: "AZ", countryEn: "Azerbaijan", countryAr: "أذربيجان", phone: "994" },
  { code: "BA", countryEn: "Bosnia and Herzegovina", countryAr: "البوسنة والهرسك", phone: "387" },
  { code: "BB", countryEn: "Barbados", countryAr: "بربادوس", phone: "1-246" },
  { code: "BD", countryEn: "Bangladesh", countryAr: "بنغلاديش", phone: "880" },
  { code: "BE", countryEn: "Belgium", countryAr: "بلجيكا", phone: "32" },
  { code: "BF", countryEn: "Burkina Faso", countryAr: "بوركينا فاسو", phone: "226" },
  { code: "BG", countryEn: "Bulgaria", countryAr: "بلغاريا", phone: "359" },
  { code: "BH", countryEn: "Bahrain", countryAr: "البحرين", phone: "973" },
  { code: "BI", countryEn: "Burundi", countryAr: "بوروندي", phone: "257" },
  { code: "BJ", countryEn: "Benin", countryAr: "بنين", phone: "229" },
  { code: "BL", countryEn: "Saint Barthelemy", countryAr: "سانت بارتيليمي", phone: "590" },
  { code: "BM", countryEn: "Bermuda", countryAr: "برمودا", phone: "1-441" },
  { code: "BN", countryEn: "Brunei Darussalam", countryAr: "بروناي دار السلام", phone: "673" },
  { code: "BO", countryEn: "Bolivia", countryAr: "بوليفيا", phone: "591" },
  { code: "BR", countryEn: "Brazil", countryAr: "البرازيل", phone: "55" },
  { code: "BS", countryEn: "Bahamas", countryAr: "البهاما", phone: "1-242" },
  { code: "BT", countryEn: "Bhutan", countryAr: "بوتان", phone: "975" },
  { code: "BV", countryEn: "Bouvet Island", countryAr: "جزيرة بوفيه", phone: "47" },
  { code: "BW", countryEn: "Botswana", countryAr: "بتسوانا", phone: "267" },
  { code: "BY", countryEn: "Belarus", countryAr: "بيلاروس", phone: "375" },
  { code: "BZ", countryEn: "Belize", countryAr: "بليز", phone: "501" },
  { code: "CA", countryEn: "Canada", countryAr: "كندا", phone: "1", "suggested": true },
  { code: "CC", countryEn: "Cocos (Keeling) Islands", countryAr: "جزر كوكوس (كيلينغ)", phone: "61" },
  { code: "CD", countryEn: "Congo, Democratic Republic of the", countryAr: "جمهورية الكونغو الديمقراطية", phone: "243" },
  { code: "CF", countryEn: "Central African Republic", countryAr: "جمهورية أفريقيا الوسطى", phone: "236" },
  { code: "CG", countryEn: "Congo, Republic of the", countryAr: "جمهورية الكونغو", phone: "242" },
  { code: "CH", countryEn: "Switzerland", countryAr: "سويسرا", phone: "41" },
  { code: "CI", countryEn: "Cote d'Ivoire", countryAr: "ساحل العاج", phone: "225" },
  { code: "CK", countryEn: "Cook Islands", countryAr: "جزر كوك", phone: "682" },
  { code: "CL", countryEn: "Chile", countryAr: "تشيلي", phone: "56" },
  { code: "CM", countryEn: "Cameroon", countryAr: "الكاميرون", phone: "237" },
  { code: "CN", countryEn: "China", countryAr: "الصين", phone: "86" },
  { code: "CO", countryEn: "Colombia", countryAr: "كولومبيا", phone: "57" },
  { code: "CR", countryEn: "Costa Rica", countryAr: "كوستاريكا", phone: "506" },
  { code: "CU", countryEn: "Cuba", countryAr: "كوبا", phone: "53" },
  { code: "CV", countryEn: "Cape Verde", countryAr: "الرأس الأخضر", phone: "238" },
  { code: "CW", countryEn: "Curacao", countryAr: "كوراساو", phone: "599" },
  { code: "CX", countryEn: "Christmas Island", countryAr: "جزيرة الكريسماس", phone: "61" },
  { code: "CY", countryEn: "Cyprus", countryAr: "قبرص", phone: "357" },
  { code: "CZ", countryEn: "Czech Republic", countryAr: "جمهورية التشيك", phone: "420" },
  { code: "DE", countryEn: "Germany", countryAr: "ألمانيا", phone: "49", "suggested": true },
  { code: "DJ", countryEn: "Djibouti", countryAr: "جيبوتي", phone: "253" },
  { code: "DK", countryEn: "Denmark", countryAr: "الدنمارك", phone: "45" },
  { code: "DM", countryEn: "Dominica", countryAr: "دومينيكا", phone: "1-767" },
  { code: "DO", countryEn: "Dominican Republic", countryAr: "جمهورية الدومينيكان", phone: "1-809" },
  { code: "DZ", countryEn: "Algeria", countryAr: "الجزائر", phone: "213" },
  { code: "EC", countryEn: "Ecuador", countryAr: "الإكوادور", phone: "593" },
  { code: "EE", countryEn: "Estonia", countryAr: "إستونيا", phone: "372" },
  { code: "EG", countryEn: "Egypt", countryAr: "مصر", phone: "20" },
  { code: "EH", countryEn: "Western Sahara", countryAr: "الصحراء الغربية", phone: "212" },
  { code: "ER", countryEn: "Eritrea", countryAr: "إريتريا", phone: "291" },
  { code: "ES", countryEn: "Spain", countryAr: "إسبانيا", phone: "34" },
  { code: "ET", countryEn: "Ethiopia", countryAr: "إثيوبيا", phone: "251" },
  { code: "FI", countryEn: "Finland", countryAr: "فنلندا", phone: "358" },
  { code: "FJ", countryEn: "Fiji", countryAr: "فيجي", phone: "679" },
  { code: "FK", countryEn: "Falkland Islands (Malvinas)", countryAr: "جزر فوكلاند (مالفيناس)", phone: "500" },
  { code: "FM", countryEn: "Micronesia, Federated States of", countryAr: "ميكرونيزيا، الولايات المتحدة الموحدة", phone: "691" },
  { code: "FO", countryEn: "Faroe Islands", countryAr: "جزر فارو", phone: "298" },
  { code: "FR", countryEn: "France", countryAr: "فرنسا", phone: "33", "suggested": true },
  { code: "GA", countryEn: "Gabon", countryAr: "الجابون", phone: "241" },
  { code: "GB", countryEn: "United Kingdom", countryAr: "المملكة المتحدة", phone: "44" },
  { code: "GD", countryEn: "Grenada", countryAr: "غرينادا", phone: "1-473" },
  { code: "GE", countryEn: "Georgia", countryAr: "جورجيا", phone: "995" },
  { code: "GF", countryEn: "French Guiana", countryAr: "غويانا الفرنسية", phone: "594" },
  { code: "GG", countryEn: "Guernsey", countryAr: "غيرنزي", phone: "44" },
  { code: "GH", countryEn: "Ghana", countryAr: "غانا", phone: "233" },
  { code: "GI", countryEn: "Gibraltar", countryAr: "جبل طارق", phone: "350" },
  { code: "GL", countryEn: "Greenland", countryAr: "جرينلاند", phone: "299" },
  { code: "GM", countryEn: "Gambia", countryAr: "غامبيا", phone: "220" },
  { code: "GN", countryEn: "Guinea", countryAr: "غينيا", phone: "224" },
  { code: "GP", countryEn: "Guadeloupe", countryAr: "غوادلوب", phone: "590" },
  { code: "GQ", countryEn: "Equatorial Guinea", countryAr: "غينيا الاستوائية", phone: "240" },
  { code: "GR", countryEn: "Greece", countryAr: "اليونان", phone: "30" },
  { code: "GS", countryEn: "South Georgia and the South Sandwich Islands", countryAr: "جورجيا الجنوبية وجزر ساندويتش الجنوبية", phone: "500" },
  { code: "GT", countryEn: "Guatemala", countryAr: "غواتيمالا", phone: "502" },
  { code: "GU", countryEn: "Guam", countryAr: "غوام", phone: "1-671" },
  { code: "GW", countryEn: "Guinea-Bissau", countryAr: "غينيا بيساو", phone: "245" },
  { code: "GY", countryEn: "Guyana", countryAr: "غيانا", phone: "592" },
  { code: "HK", countryEn: "Hong Kong", countryAr: "هونغ كونغ", phone: "852" },
  { code: "HM", countryEn: "Heard Island and McDonald Islands", countryAr: "جزيرة هيرد وجزر ماكدونالد", phone: "672" },
  { code: "HN", countryEn: "Honduras", countryAr: "هندوراس", phone: "504" },
  { code: "HR", countryEn: "Croatia", countryAr: "كرواتيا", phone: "385" },
  { code: "HT", countryEn: "Haiti", countryAr: "هايتي", phone: "509" },
  { code: "HU", countryEn: "Hungary", countryAr: "هنغاريا", phone: "36" },
  { code: "ID", countryEn: "Indonesia", countryAr: "إندونيسيا", phone: "62" },
  { code: "IE", countryEn: "Ireland", countryAr: "أيرلندا", phone: "353" },
  { code: "IL", countryEn: "Israel", countryAr: "إسرائيل", phone: "972" },
  { code: "IM", countryEn: "Isle of Man", countryAr: "جزيرة مان", phone: "44" },
  { code: "IN", countryEn: "India", countryAr: "الهند", phone: "91" },
  { code: "IO", countryEn: "British Indian Ocean Territory", countryAr: "إقليم المحيط الهندي البريطاني", phone: "246" },
  { code: "IQ", countryEn: "Iraq", countryAr: "العراق", phone: "964" },
  { code: "IR", countryEn: "Iran, Islamic Republic of", countryAr: "إيران، الجمهورية الإسلامية", phone: "98" },
  { code: "IS", countryEn: "Iceland", countryAr: "آيسلندا", phone: "354" },
  { code: "IT", countryEn: "Italy", countryAr: "إيطاليا", phone: "39" },
  { code: "JE", countryEn: "Jersey", countryAr: "جيرزي", phone: "44" },
  { code: "JM", countryEn: "Jamaica", countryAr: "جامايكا", phone: "1-876" },
  { code: "JO", countryEn: "Jordan", countryAr: "الأردن", phone: "962" },
  { code: "JP", countryEn: "Japan", countryAr: "اليابان", phone: "81", "suggested": true },
  { code: "KE", countryEn: "Kenya", countryAr: "كينيا", phone: "254" },
  { code: "KG", countryEn: "Kyrgyzstan", countryAr: "قيرغيزستان", phone: "996" },
  { code: "KH", countryEn: "Cambodia", countryAr: "كمبوديا", phone: "855" },
  { code: "KI", countryEn: "Kiribati", countryAr: "كيريباتي", phone: "686" },
  { code: "KM", countryEn: "Comoros", countryAr: "جزر القمر", phone: "269" },
  { code: "KN", countryEn: "Saint Kitts and Nevis", countryAr: "سانت كيتس ونيفيس", phone: "1-869" },
  { code: "KP", countryEn: "Korea, Democratic People's Republic of", countryAr: "كوريا، الجمهورية الشعبية الديمقراطية", phone: "850" },
  { code: "KR", countryEn: "Korea, Republic of", countryAr: "كوريا، جمهورية", phone: "82" },
  { code: "KW", countryEn: "Kuwait", countryAr: "الكويت", phone: "965" },
  { code: "KY", countryEn: "Cayman Islands", countryAr: "جزر الكايمن", phone: "1-345" },
  { code: "KZ", countryEn: "Kazakhstan", countryAr: "كازاخستان", phone: "7" },
  { code: "LA", countryEn: "Lao People's Democratic Republic", countryAr: "جمهورية لاو الديمقراطية الشعبية", phone: "856" },
  { code: "LB", countryEn: "Lebanon", countryAr: "لبنان", phone: "961" },
  { code: "LC", countryEn: "Saint Lucia", countryAr: "سانت لوسيا", phone: "1-758" },
  { code: "LI", countryEn: "Liechtenstein", countryAr: "ليختنشتاين", phone: "423" },
  { code: "LK", countryEn: "Sri Lanka", countryAr: "سريلانكا", phone: "94" },
  { code: "LR", countryEn: "Liberia", countryAr: "ليبيريا", phone: "231" },
  { code: "LS", countryEn: "Lesotho", countryAr: "ليسوتو", phone: "266" },
  { code: "LT", countryEn: "Lithuania", countryAr: "ليتوانيا", phone: "370" },
  { code: "LU", countryEn: "Luxembourg", countryAr: "لوكسمبورغ", phone: "352" },
  { code: "LV", countryEn: "Latvia", countryAr: "لاتفيا", phone: "371" },
  { code: "LY", countryEn: "Libya", countryAr: "ليبيا", phone: "218" },
  { code: "MA", countryEn: "Morocco", countryAr: "المغرب", phone: "212" },
  { code: "MC", countryEn: "Monaco", countryAr: "موناكو", phone: "377" },
  { code: "MD", countryEn: "Moldova, Republic of", countryAr: "مولدوفا، جمهورية", phone: "373" },
  { code: "ME", countryEn: "Montenegro", countryAr: "الجبل الأسود", phone: "382" },
  { code: "MF", countryEn: "Saint Martin (French part)", countryAr: "سانت مارتن (الجزء الفرنسي)", phone: "590" },
  { code: "MG", countryEn: "Madagascar", countryAr: "مدغشقر", phone: "261" },
  { code: "MH", countryEn: "Marshall Islands", countryAr: "جزر مارشال", phone: "692" },
  { code: "MK", countryEn: "Macedonia, the Former Yugoslav Republic of", countryAr: "مقدونيا، جمهورية يوغوسلافيا السابقة", phone: "389" },
  { code: "ML", countryEn: "Mali", countryAr: "مالي", phone: "223" },
  { code: "MM", countryEn: "Myanmar", countryAr: "ميانمار", phone: "95" },
  { code: "MN", countryEn: "Mongolia", countryAr: "منغوليا", phone: "976" },
  { code: "MO", countryEn: "Macao", countryAr: "ماكاو", phone: "853" },
  { code: "MP", countryEn: "Northern Mariana Islands", countryAr: "جزر ماريانا الشمالية", phone: "1-670" },
  { code: "MQ", countryEn: "Martinique", countryAr: "مارتينيك", phone: "596" },
  { code: "MR", countryEn: "Mauritania", countryAr: "موريتانيا", phone: "222" },
  { code: "MS", countryEn: "Montserrat", countryAr: "مونتسيرات", phone: "1-664" },
  { code: "MT", countryEn: "Malta", countryAr: "مالطا", phone: "356" },
  { code: "MU", countryEn: "Mauritius", countryAr: "موريشيوس", phone: "230" },
  { code: "MV", countryEn: "Maldives", countryAr: "جزر المالديف", phone: "960" },
  { code: "MW", countryEn: "Malawi", countryAr: "ملاوي", phone: "265" },
  { code: "MX", countryEn: "Mexico", countryAr: "المكسيك", phone: "52" },
  { code: "MY", countryEn: "Malaysia", countryAr: "ماليزيا", phone: "60" },
  { code: "MZ", countryEn: "Mozambique", countryAr: "موزمبيق", phone: "258" },
  { code: "NA", countryEn: "Namibia", countryAr: "ناميبيا", phone: "264" },
  { code: "NC", countryEn: "New Caledonia", countryAr: "كاليدونيا الجديدة", phone: "687" },
  { code: "NE", countryEn: "Niger", countryAr: "النيجر", phone: "227" },
  { code: "NF", countryEn: "Norfolk Island", countryAr: "جزيرة نورفولك", phone: "672" },
  { code: "NG", countryEn: "Nigeria", countryAr: "نيجيريا", phone: "234" },
  { code: "NI", countryEn: "Nicaragua", countryAr: "نيكاراغوا", phone: "505" },
  { code: "NL", countryEn: "Netherlands", countryAr: "هولندا", phone: "31" },
  { code: "NO", countryEn: "Norway", countryAr: "النرويج", phone: "47" },
  { code: "NP", countryEn: "Nepal", countryAr: "نيبال", phone: "977" },
  { code: "NR", countryEn: "Nauru", countryAr: "ناورو", phone: "674" },
  { code: "NU", countryEn: "Niue", countryAr: "نيوي", phone: "683" },
  { code: "NZ", countryEn: "New Zealand", countryAr: "نيوزيلندا", phone: "64" },
  { code: "OM", countryEn: "Oman", countryAr: "عمان", phone: "968" },
  { code: "PA", countryEn: "Panama", countryAr: "بنما", phone: "507" },
  { code: "PE", countryEn: "Peru", countryAr: "بيرو", phone: "51" },
  { code: "PF", countryEn: "French Polynesia", countryAr: "بولينيزيا الفرنسية", phone: "689" },
  { code: "PG", countryEn: "Papua New Guinea", countryAr: "بابوا غينيا الجديدة", phone: "675" },
  { code: "PH", countryEn: "Philippines", countryAr: "الفلبين", phone: "63" },
  { code: "PK", countryEn: "Pakistan", countryAr: "باكستان", phone: "92" },
  { code: "PL", countryEn: "Poland", countryAr: "بولندا", phone: "48" },
  { code: "PM", countryEn: "Saint Pierre and Miquelon", countryAr: "سان بيير وميكلون", phone: "508" },
  { code: "PN", countryEn: "Pitcairn", countryAr: "بيتكيرن", phone: "870" },
  { code: "PR", countryEn: "Puerto Rico", countryAr: "بورتوريكو", phone: "1" },
  { code: "PS", countryEn: "Palestine, State of", countryAr: "فلسطين، دولة", phone: "970" },
  { code: "PT", countryEn: "Portugal", countryAr: "البرتغال", phone: "351" },
  { code: "PW", countryEn: "Palau", countryAr: "بالاو", phone: "680" },
  { code: "PY", countryEn: "Paraguay", countryAr: "باراغواي", phone: "595" },
  { code: "QA", countryEn: "Qatar", countryAr: "قطر", phone: "974" },
  { code: "RE", countryEn: "Reunion", countryAr: "ريونيون", phone: "262" },
  { code: "RO", countryEn: "Romania", countryAr: "رومانيا", phone: "40" },
  { code: "RS", countryEn: "Serbia", countryAr: "صربيا", phone: "381" },
  { code: "RU", countryEn: "Russian Federation", countryAr: "الاتحاد الروسي", phone: "7" },
  { code: "RW", countryEn: "Rwanda", countryAr: "رواندا", phone: "250" },
  { code: "SA", countryEn: "Saudi Arabia", countryAr: "المملكة العربية السعودية", phone: "966" },
  { code: "SB", countryEn: "Solomon Islands", countryAr: "جزر سليمان", phone: "677" },
  { code: "SC", countryEn: "Seychelles", countryAr: "سيشل", phone: "248" },
  { code: "SD", countryEn: "Sudan", countryAr: "السودان", phone: "249" },
  { code: "SE", countryEn: "Sweden", countryAr: "السويد", phone: "46" },
  { code: "SG", countryEn: "Singapore", countryAr: "سنغافورة", phone: "65" },
  { code: "SH", countryEn: "Saint Helena", countryAr: "سانت هيلينا", phone: "290" },
  { code: "SI", countryEn: "Slovenia", countryAr: "سلوفينيا", phone: "386" },
  { code: "SJ", countryEn: "Svalbard and Jan Mayen", countryAr: "سفالبارد وجان ماين", phone: "47" },
  { code: "SK", countryEn: "Slovakia", countryAr: "سلوفاكيا", phone: "421" },
  { code: "SL", countryEn: "Sierra Leone", countryAr: "سيراليون", phone: "232" },
  { code: "SM", countryEn: "San Marino", countryAr: "سان مارينو", phone: "378" },
  { code: "SN", countryEn: "Senegal", countryAr: "السنغال", phone: "221" },
  { code: "SO", countryEn: "Somalia", countryAr: "الصومال", phone: "252" },
  { code: "SR", countryEn: "Suriname", countryAr: "سورينام", phone: "597" },
  { code: "SS", countryEn: "South Sudan", countryAr: "جنوب السودان", phone: "211" },
  { code: "ST", countryEn: "Sao Tome and Principe", countryAr: "ساو تومي وبرينسيب", phone: "239" },
  { code: "SV", countryEn: "El Salvador", countryAr: "السلفادور", phone: "503" },
  { code: "SX", countryEn: "Sint Maarten (Dutch part)", countryAr: "سانت مارتن (الجزء الهولندي)", phone: "1-721" },
  { code: "SY", countryEn: "Syrian Arab Republic", countryAr: "الجمهورية العربية السورية", phone: "963" },
  { code: "SZ", countryEn: "Swaziland", countryAr: "سوازيلاند", phone: "268" },
  { code: "TC", countryEn: "Turks and Caicos Islands", countryAr: "جزر توركس وكايكوس", phone: "1-649" },
  { code: "TD", countryEn: "Chad", countryAr: "تشاد", phone: "235" },
  { code: "TF", countryEn: "French Southern Territories", countryAr: "المقاطعات الجنوبية الفرنسية", phone: "262" },
  { code: "TG", countryEn: "Togo", countryAr: "توغو", phone: "228" },
  { code: "TH", countryEn: "Thailand", countryAr: "تايلاند", phone: "66" },
  { code: "TJ", countryEn: "Tajikistan", countryAr: "طاجيكستان", phone: "992" },
  { code: "TK", countryEn: "Tokelau", countryAr: "توكيلاو", phone: "690" },
  { code: "TL", countryEn: "Timor-Leste", countryAr: "تيمور الشرقية", phone: "670" },
  { code: "TM", countryEn: "Turkmenistan", countryAr: "تركمانستان", phone: "993" },
  { code: "TN", countryEn: "Tunisia", countryAr: "تونس", phone: "216" },
  { code: "TO", countryEn: "Tonga", countryAr: "تونغا", phone: "676" },
  { code: "TR", countryEn: "Turkey", countryAr: "تركيا", phone: "90" },
  { code: "TT", countryEn: "Trinidad and Tobago", countryAr: "ترينيداد وتوباغو", phone: "1-868" },
  { code: "TV", countryEn: "Tuvalu", countryAr: "توفالو", phone: "688" },
  { code: "TW", countryEn: "Taiwan, Republic of China", countryAr: "تايوان، جمهورية الصين", phone: "886" },
  { code: "TZ", countryEn: "United Republic of Tanzania", countryAr: "جمهورية تنزانيا المتحدة", phone: "255" },
  { code: "UA", countryEn: "Ukraine", countryAr: "أوكرانيا", phone: "380" },
  { code: "UG", countryEn: "Uganda", countryAr: "أوغندا", phone: "256" },
  { code: "US", countryEn: "United States", countryAr: "الولايات المتحدة", phone: "1", "suggested": true },
  { code: "UY", countryEn: "Uruguay", countryAr: "أوروغواي", phone: "598" },
  { code: "UZ", countryEn: "Uzbekistan", countryAr: "أوزبكستان", phone: "998" },
  { code: "VA", countryEn: "Holy See (Vatican City State)", countryAr: "الكرسي الرسولي (الفاتيكان)", phone: "379" },
  { code: "VC", countryEn: "Saint Vincent and the Grenadines", countryAr: "سانت فينسنت والجرينادين", phone: "1-784" },
  { code: "VE", countryEn: "Venezuela", countryAr: "فنزويلا", phone: "58" },
  { code: "VG", countryEn: "British Virgin Islands", countryAr: "جزر العذراء البريطانية", phone: "1-284" },
  { code: "VI", countryEn: "US Virgin Islands", countryAr: "جزر العذراء الأمريكية", phone: "1-340" },
  { code: "VN", countryEn: "Vietnam", countryAr: "فيتنام", phone: "84" },
  { code: "VU", countryEn: "Vanuatu", countryAr: "فانواتو", phone: "678" },
  { code: "WF", countryEn: "Wallis and Futuna", countryAr: "والس وفوتونا", phone: "681" },
  { code: "WS", countryEn: "Samoa", countryAr: "ساموا", phone: "685" },
  { code: "XK", countryEn: "Kosovo", countryAr: "كوسوفو", phone: "383" },
  { code: "YE", countryEn: "Yemen", countryAr: "اليمن", phone: "967" },
  { code: "YT", countryEn: "Mayotte", countryAr: "مايوت", phone: "262" },
  { code: "ZA", countryEn: "South Africa", countryAr: "جنوب أفريقيا", phone: "27" },
  { code: "ZM", countryEn: "Zambia", countryAr: "زامبيا", phone: "260" },
  { code: "ZW", countryEn: "Zimbabwe", countryAr: "زيمبابوي", phone: "263" }
]